# 1. 판다스 기초

## 1. 판다스(Pandas)

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/500px-Pandas_logo.svg.png' width="400" height ="170" /><br>

▶ 공식문서: https://pandas.pydata.org/docs/index.html

- 파이썬의 대표적인 데이터 분석 도구

- 엑셀과 같이 **행(row)**과 **열(columns)**로 된 데이터 구조를 다룸

- 라이브러리 로드: `import pandas as pd`

- **판다스의 데이터 타입**

    > **Series (시리즈)**<br>
    > 수학적으로 **벡터**의 형태를 가짐 (1차원) <br>
    > 각 요소에 인덱스를 사용할 수 있다 <br>
    > 예시: [1,2,3]

    > **DataFrame (데이터 프레임)** <br>
    > 수학적으로 **행렬**의 형태를 가짐 (2차원) <br>
    > **열(Column)**과 **행(row)**으로 구성 <br>
    > 예시: [ [1,2,3], [4,5,6] ]

<img src='https://pandas.pydata.org/docs/_images/01_table_dataframe.svg' width="700" height ="400" /><br>

In [ ]:
# 판다스 불러오기
import pandas as pd
# 넘파이 불러오기
import numpy as np

▶ 시리즈 만들기 `pd.Series(데이터배열)`

- 1차원 데이터구조의 배열, 다양한 데이터 타입 사용 가능

- 데이터를 다루는 기본 단위

- 인덱스를 사용할 수 있음

    > 인덱스(index)와 값(value)로 이루어짐

- 데이터프레임에서 한 열을 나타내는 자료구조

In [ ]:
# 시리즈 만들기1
data = [1,2,3,4,5]
pd.Series(data)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
# 시리즈 만들기2 - 인덱스 지정
pd.Series(data, index=['a','b','c','d','e'])

a    1
b    2
c    3
d    4
e    5
dtype: int64

**numpy**

- 배열을 다룰 수 있는 파이썬 라이브러리. 수치 계산에 특화됨

- 배열의 종류

    <img src='https://velog.velcdn.com/images/jhdai_ly/post/b5e3759c-8ae2-45e7-a89a-e177b70e9fdc/image.png' width="600" height ="300" />

    > 1차원 배열: 벡터, 배열 a 안에 리스트 [1,2,3]이 들어있는 모양
    >
    > 2차원 배열: 행렬, 배열 a 안에 [[1,2,3],[4,5,6]] 두 개의 리스트가 들어가 있는 모양
    >
    > 3차원 배열: 텐서, 배열 a 안에 3개의 리스트가 들어감 [[[]]]

- 넘파이 배열 만들기: `np.array(시퀀스자료형)`

In [ ]:
# 시리즈 만들기3 - 넘파이 배열
data = np.array([1,2,3])
pd.Series(data)

0    1
1    2
2    3
dtype: int64

▶ 데이터프레임 만들기

- 2차원 데이터 구조의 배열, 행과 열이 있는 테이블 데이터 구조

- 시리즈가 모여 데이터프레임이 됨

- 각 열은 각각의 데이터 타입을 가짐

In [ ]:
# 데이터프레임 만들기1 - 2차원 배열로 만들기
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
pd.DataFrame(data)

   0  1  2
0  1  2  3
1  4  5  6
2  7  8  9

In [ ]:
# 데이터프레임 만들기2 - 컬럼 지정하기
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
pd.DataFrame(data, columns=['A','B','C'])

   a  b  c
0  1  2  3
1  4  5  6
2  7  8  9

## 2. 데이터 불러오기

▶ CSV파일 데이터 불러오기
> **pd.read_csv (파일경로), pd.read_excel (파일경로)** <br>
> 이때 파일경로는 문자열 형태로 입력
>
> 예) pd.read_csv("/content/sample_data/sample.csv") <br>

In [ ]:
# 데이터 불러오기
# 파일 경로 = "https://raw.githubusercontent.com/agtechresearch/LectureMLbasic/refs/heads/main/csv/housing.csv"

cali_house = pd.read_csv("https://raw.githubusercontent.com/agtechresearch/LectureMLbasic/refs/heads/main/csv/housing.csv")
cali_house

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

▶ 🏘️ 캘리포니아 집값 데이터셋

- **longitude**: 위도

- **latitude**: 경도

- **housing_median_age**: 건축물 중위연령

- **total_rooms**: 방의 총 개수

- **total_bedrooms**: 침실 총 개수

- **population**: 인구

- **households**: 가구수

- **median_income**: 중위소득

- **median_house_value**: 주택 중위가격

- **ocean_proximity**: 해안 근접도

## 3. 데이터셋 확인
▶ 전반적인 데이터셋 정보 확인 (**.info()**) <br>
> 데이터셋의 **컬럼정보와 값의 수, 각 컬럼별 데이터타입, 행의 갯수 등**의 정보 <br>

In [ ]:
# 데이터셋 정보 확인
cali_house.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

▶ 앞부분 (**.head()**), 마지막부분 (**.tail()**)
> 괄호안에 숫자를 넣어 **앞에서 n개 행(row), 혹은 끝에서 n개 행**을 가져오기

In [ ]:
# 데이터 앞 부분 확인하기
cali_house.head(10)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
9,-122.25,37.84,52.0,3549.0,707.0,1551.0,714.0,3.6912,261100.0,NEAR BAY

In [ ]:
# 데이터 뒷 부분 확인하기
cali_house.tail()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

▶ 데이터셋 기술통계량 확인
> **.describe()** <br>
> 데이터프레임 내부 각 컬럼에 대한 **count, mean, min, max, 사분위값, std 등의 항목을 자동으로 계산** <br>
> .describe() 외 **.min(), .max(), .mean()** 등으로 특정 항목만 구할수도 있음
>

In [ ]:
# 데이터의 통계량 확인하기
cali_house.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

▶ 데이터셋 정렬하기

> **sort_index()** <br>
>
>  index 기준으로 정렬
>
>  default는 오름차순이며 ascending의 설정으로 조정가능
>>
>> ascending=False (내림차순으로 정렬)
>

> **sort_values(by =기준컬럼)** <br>
>
>  **값**을 기준으로 행을 정렬
>
>  두개 이상의 컬럼을 지정하여 정렬할 수 있음
>
>  ascending=True (오름차순)이 기본
>
>  컬럼별로 오름차순/내림차순 설정 가능
>

➕ 원본에도 똑같이 적용하고 싶을 경우 **inplace = True**

In [ ]:
# 인덱스 기준으로 정렬하기
cali_house.sort_index(ascending=False).head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND

In [ ]:
# 값을 기준으로 정렬하기(원하는 값 기준으로 정렬해보세요)
cali_house.sort_values(by="population").head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
5342,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.536,350000.0,<1H OCEAN
12458,-114.62,33.62,26.0,18.0,3.0,5.0,3.0,0.536,275000.0,INLAND
3126,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.375,137500.0,INLAND
12286,-116.95,33.86,1.0,6.0,2.0,8.0,2.0,1.625,55000.0,INLAND
18210,-122.06,37.39,26.0,18.0,4.0,8.0,4.0,3.750,375000.0,NEAR BAY

In [ ]:
# 두 개 이상의 컬럼을 기준으로 정렬하기
cali_house.sort_values(by=['population', 'households'], ascending=[True, False]).head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
5342,-118.44,34.04,16.0,18.0,6.0,3.0,4.0,0.536,350000.0,<1H OCEAN
12458,-114.62,33.62,26.0,18.0,3.0,5.0,3.0,0.536,275000.0,INLAND
3126,-117.79,35.21,4.0,2.0,2.0,6.0,2.0,2.375,137500.0,INLAND
3125,-117.76,35.22,4.0,18.0,3.0,8.0,6.0,1.625,275000.0,INLAND
18210,-122.06,37.39,26.0,18.0,4.0,8.0,4.0,3.750,375000.0,NEAR BAY

## 4. 데이터셋 가공
▶ 데이터를 통해 의미있는 결과를 얻기 위해 원본 데이터에서 가공하거나 원하는 데이터를 선택할 수 있음<br>

### (1) 데이터프레임에서 원하는 특정 행 또는 열 가져오기

**1. 열 인덱싱**
> `df['column']`: 데이터프레임에서 열 하나 가져오기
>
> `df[['column']]`: 열 하나 가져오기, 데이터프레임 형태로 출력
>
> `df[['column1','column2']]`: 여러개의 열을 부를 때는 리스트로

In [ ]:
# 데이터프레임에서 열 하나 가져오기
cali_house['population']

0         322.0
1        2401.0
2         496.0
3         558.0
4         565.0
          ...
20635     845.0
20636     356.0
20637    1007.0
20638     741.0
20639    1387.0
Name: population, Length: 20640, dtype: float64

In [ ]:
# 데이터프레임에서 열 가져오는데 데이터프레임 형태로 보기
cali_house[['population']]

       population
0           322.0
1          2401.0
2           496.0
3           558.0
4           565.0
...           ...
20635       845.0
20636       356.0
20637      1007.0
20638       741.0
20639      1387.0

[20640 rows x 1 columns]

In [ ]:
# 여러개의 열 가져오기
cali_house[['longitude','latitude']]

       longitude  latitude
0        -122.23     37.88
1        -122.22     37.86
2        -122.24     37.85
3        -122.25     37.85
4        -122.25     37.85
...          ...       ...
20635    -121.09     39.48
20636    -121.21     39.49
20637    -121.22     39.43
20638    -121.32     39.43
20639    -121.24     39.37

[20640 rows x 2 columns]

**2. 행 인덱싱**

> 슬라이싱 형식으로 가져옴

In [ ]:
# 데이터프레임에서 3번행부터 8번행까지 가져오기
cali_house[3:9]

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
6,-122.25,37.84,52.0,2535.0,489.0,1094.0,514.0,3.6591,299200.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY

### (2) 데이터셋 결측치 확인
>  실제 데이터셋 에서는 **측정되지 않았거나, 누락 등 알수없는 이유**로 데이터프레임 상에서 **NaN(Not a Number)값**인 데이터가 있음 <br>
>
> 특히 NaN값은 제거하거나 다른 적절한 값으로 채우지 않을 경우, **연산시 오류**를 일으키므로 데이터셋 가공 전 **꼭 확인** 필요
>
> * 결측값 확인 <br>
>  **isnull(), isnull().sum()**
>
> * 결측값 채우기 <br>
>  **fillna(특정값)**

In [ ]:
# 결측값이 각 컬럼에 총 몇 개 있는지 알아보자
cali_house.isnull().sum()

longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64

In [ ]:
# 결측치 채우기
cali_house_1 = cali_house.fillna(0) # 다른 변수에 따로 지정

In [ ]:
cali_house_1.isnull().sum()

longitude             0
latitude              0
housing_median_age    0
total_rooms           0
total_bedrooms        0
population            0
households            0
median_income         0
median_house_value    0
ocean_proximity       0
dtype: int64

▶ 데이터 삭제하기

* 결측값이 있는 행, 열 제거 **dropna()**
>
> `dropna()`: 어떤 행이든 하나 이상의 결측치가 있으면 해당 행 제거
>
>  `dropna(axis=1)`: 어떤 열이든 하나 이상의 결측치가 있으면 해당 열 제거
>
> `dropna(subset=['컬럼'])`: 특정 열에 결측치가 있는 행만 제거

> axis=0 : 행방향(결측치가 있는 행 제거) <br> axis=1 : 열방향(결측치가 있는 열 제거)

In [ ]:
#데이터 생성
cafe1 = {
        "Name" : ["아이스아메리카노", "카페라떼", "로얄밀크티","자몽 스파클링"],
        "Price": [2600, 2800, np.NaN, 3800],
        "Sales": [200,np.NaN,50,35]
    }
cafe_df1 = pd.DataFrame(cafe1)
cafe_df1

       Name   Price  Sales
0  아이스아메리카노  2600.0  200.0
1      카페라떼  2800.0    NaN
2     로얄밀크티     NaN   50.0
3   자몽 스파클링  3800.0   35.0

In [ ]:
# 결측치가 있는 행 제거(cafe_df1)
cafe_df1.dropna()

       Name   Price  Sales
0  아이스아메리카노  2600.0  200.0
3   자몽 스파클링  3800.0   35.0

▶ 데이터 삭제하기

* 원하는 행, 열 제거 **drop()**
>
> 행(하나): 데이터프레임**.drop(인덱스,axis=0)**
>
> 행(여러개): 데이터프레임**.drop(index=삭제할 인덱스 리스트)**
>
> 열(하나): 데이터프레임**.drop('컬럼명', axis=1)**
>
> 열(여러개): 데이터프레임**.drop(['컬럼1','컬럼2'], axis=1)**

In [ ]:
# 행 하나 삭제
cali_house.drop(2).head(3)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY

In [ ]:
# 여러개의 행 삭제
cali_house.drop(index=[4,6,9]).head(8)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
5,-122.25,37.85,52.0,919.0,213.0,413.0,193.0,4.0368,269700.0,NEAR BAY
7,-122.25,37.84,52.0,3104.0,687.0,1157.0,647.0,3.1200,241400.0,NEAR BAY
8,-122.26,37.84,42.0,2555.0,665.0,1206.0,595.0,2.0804,226700.0,NEAR BAY
10,-122.26,37.85,52.0,2202.0,434.0,910.0,402.0,3.2031,281500.0,NEAR BAY

In [ ]:
# 하나의 열 삭제
cali_house.drop('total_bedrooms', axis=1, inplace=True)
cali_house

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,1387.0,530.0,2.3886,89400.0,INLAND

### (3) 그룹 연산을 통해 특정 조건에 따라 그룹 나누기
> **groupby('컬럼')** <br>
> 주로 그룹연산과 함께 mean(), size(), sum()등을 사용 <br>
> + 컬럼값에 [ ]를 이용하여 [컬럼1, 컬럼2] 형식으로 입력할 경우, 컬럼1의 값들 안에서 컬럼2의 값으로 분리된다.
>

In [ ]:
# 해안근접도(5개의 범주)에 따른 각 컬럼의 평균 알아보기
cali_house.groupby('ocean_proximity').sum().head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
ocean_proximity,,,,,,,,,
<1H OCEAN,-1085793.19,315745.43,267495.0,24012547.0,4937435.0,13889374.0,4730118.0,38651.5100,2.193410e+09
INLAND,-784370.82,240630.21,159005.0,17803933.0,3468095.0,9112744.0,3127759.0,21022.1353,8.176001e+08
ISLAND,-591.77,166.79,212.0,7873.0,2102.0,3340.0,1383.0,13.7221,1.902200e+06
NEAR BAY,-279976.99,86564.42,86402.0,5710320.0,1167195.0,2817427.0,1118931.0,9555.9061,5.935962e+08
NEAR OCEAN,-317185.93,92334.77,78005.0,6867477.0,1415482.0,3598955.0,1332308.0,10647.3760,6.629955e+08

In [ ]:
# 해안근접도와 인구수에 따른 각 컬럼의 최소값 알아보기
cali_house.groupby(['ocean_proximity','total_rooms']).min()

                             housing_median_age  population  households  \
ocean_proximity total_rooms
<1H OCEAN       11.0                       46.0        24.0        13.0
                15.0                       36.0        15.0         6.0
                18.0                       16.0         3.0         4.0
                20.0                       16.0        15.0         5.0
                21.0                       36.0        21.0         9.0
...                                         ...         ...         ...
NEAR OCEAN      18123.0                     4.0      7301.0      2964.0
                20944.0                    11.0      8738.0      3441.0
                23866.0                     7.0      9873.0      4012.0
                23915.0                     4.0     10877.0      3958.0
                30405.0                     9.0     12873.0      3931.0

                             median_income  median_house_value
ocean_proximity total_rooms
<1H OCEAN       11.0                2.8750            162500.0
                15.0                0.4999            162500.0
                18.0                0.5360            350000.0
                20.0                3.8750            450000.0
                21.0                2.3750            175000.0
...                                    ...                 ...
NEAR OCEAN      18123.0             6.3570            322500.0
                20944.0             4.3762            215500.0
                23866.0             5.4032            318500.0
                23915.0             4.6357            244900.0
                30405.0             8.0137            399200.0

[11718 rows x 5 columns]

In [ ]:
# 두 개 이상의 연산 사용하기
cali_house.groupby(['ocean_proximity']).agg(['mean','sum'])[['population']].head()

                  population
                        mean         sum
ocean_proximity
<1H OCEAN        1520.290499  13889374.0
INLAND           1391.046252   9112744.0
ISLAND            668.000000      3340.0
NEAR BAY         1230.317467   2817427.0
NEAR OCEAN       1354.008653   3598955.0

### (4) 데이터셋 합치기
> * **.concat( [ 합칠 데이터프레임 나열 ] )** <br>
>  두 데이터프레임을 **단순하게 합칠 때** 사용 <br>
> 행 또는 열 방향으로 연결 <br>
> 기본값: `axis=0` (행 방향, 위/아래 방향으로 연결) <br>
> `axis=1` (열 방향, 좌/우 방향으로 연결)
>
> * **.merge( 데이터프레임1, 데이터프레임2, on=공통컬럼명 )** <br>
>  두 데이터프레임을 **공통된 항목(key값,컬럼)을 기준으로 합칠 때** 사용(병합)
>

In [ ]:
# 데이터 생성
# 데이터 1
cafe = {
        "Name" : ["아이스아메리카노", "카페라떼", "로얄밀크티","자몽 스파클링"],
        "Price": [2600, 2800, 4500, 3800],
    }
df1 = pd.DataFrame(cafe)
df1

       Name  Price
0  아이스아메리카노   2600
1      카페라떼   2800
2     로얄밀크티   4500
3   자몽 스파클링   3800

In [ ]:
# 데이터 2
sales = {"Sales": [200,100,50,35]}
df2 = pd.DataFrame(sales)
df2

   Sales
0    200
1    100
2     50
3     35

In [ ]:
# 두 데이터 합치기 - 행과 행
pd.concat([df1,df2], axis=0)

       Name   Price  Sales
0  아이스아메리카노  2600.0    NaN
1      카페라떼  2800.0    NaN
2     로얄밀크티  4500.0    NaN
3   자몽 스파클링  3800.0    NaN
0       NaN     NaN  200.0
1       NaN     NaN  100.0
2       NaN     NaN   50.0
3       NaN     NaN   35.0

In [ ]:
# 두 데이터 합치기 - 열과 열
pd.concat([df1,df2], axis=1)

       Name  Price  Sales
0  아이스아메리카노   2600    200
1      카페라떼   2800    100
2     로얄밀크티   4500     50
3   자몽 스파클링   3800     35